# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: secure-ai-app-build-demo
metadata:
  template: secure-ai-app-build-demo@0.0.1-beta
services:
  # Not using remoteBuild due to private endpoint usage
  aca:
    project: ./src
    language: py
    host: containerapp
hooks:
  postprovision:
    windows:
      shell: pwsh
      run: ./scripts/write_env.ps1
      continueOnError: true
    posix:
      shell: sh
      run: ./scripts/output_vpn.sh;./scripts/approve_link.sh;./scripts/write_env.sh
      continueOnError: true
pipeline:
  variables:
    - AZURE_OPENAI_RESOURCE
    - AZURE_OPENAI_RESOURCE_LOCATION
    - AZURE_OPENAI_SKU_NAME
